name: build_old
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        with_plugin: [ false, true ]
        ubuntu_distribution: [ focal ]
        ros_distribution: [ galactic, rolling ]
      fail-fast: false
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu_distribution }}-latest

    steps:
      - name: setup ROS environment
        uses: ros-tooling/setup-ros@v0.4
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: install_clang
        run: sudo apt update && sudo apt install -y clang clang-tools lld
      # TODO: remove this when uncrustify 0.72 is fixed https://github.com/uncrustify/uncrustify/issues/3191
      - name: hack for uncrustify 0.72 problems
        run: wget http://mirrors.kernel.org/ubuntu/pool/universe/u/uncrustify/uncrustify_0.69.0+dfsg1-1build1_amd64.deb && dpkg -i uncrustify_0.69.0+dfsg1-1build1_amd64.deb && apt install -f -y
        if: ${{ matrix.ubuntu_distribution == 'jammy' || matrix.ubuntu_distribution == 'rolling'}}
      # TODO: Remove this step when the incompatibility between libunwind14 and libundind dissapears https://github.com/open-rmf/rmf_traffic_editor/issues/439
      - name: Horrible hack for libceres
        run: |
          apt-get remove -y --purge libc++-dev || true 
          apt-get remove -y --purge libc++abi-dev || true
          apt-get remove -y --purge libunwind-14-dev || true 
          apt-get remove -y --purge libunwind-14-dev || true 
          apt-get remove -y --purge libunwind-dev || true
          apt -y autoremove
        if: ${{ matrix.ubuntu_distribution == 'jammy' || matrix.ubuntu_distribution == 'rolling'}}
      # TODO: https://github.com/open-rmf/rmf/pull/202#pullrequestreview-1100045417
      - name: fix cryptography==2.8
        run: pip3 install cryptography==2.8
#      - name: non-ros-deps
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y git cmake wget libyaml-cpp-dev qt5-default libceres-dev
      - name: gazebo plugin-deps
        if: ${{ matrix.with_plugin == true }}
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable ${{ matrix.ubuntu_distribution }} main" > /etc/apt/sources.list.d/gazebo-stable.list
          wget https://packages.osrfoundation.org/gazebo.key -O - | apt-key add -
          sudo apt-get update
          sudo apt-get install -y libignition-plugin-dev libignition-common3-dev
          sudo apt-get install -y libopencv-dev libopencv-videoio-dev libignition-plugin-dev libignition-common3-dev
      - name: build
        uses: ros-tooling/action-ros-ci@v0.2
        env:
          CC: clang
          CXX: clang++
          QT_QPA_PLATFORM: offscreen
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          # build all packages listed in the meta package
          package-name: |
            rmf_traffic_editor
            rmf_building_map_tools
            rmf_traffic_editor_assets
            rmf_traffic_editor_test_maps
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/open-rmf/rmf/main/rmf.repos
          extra-cmake-args: "-DNO_DOWNLOAD_MODELS=True"
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc", "lld"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
